name: 'Travis Reynolds'
description: 'An action to automatically deploy a JammeryHQ starter.'
author: 'JammeryHQ'
inputs:
  connection-string:
    description: 'Azure Container Connection String'
    default: ''
  container-name:
    description: 'Azure Container Name'
    default: ''
  milliseconds:
    description: 'milliseconds to wait'
    default: '2000'
runs:
  using: 'node12'
  main: 'dist/index.js'
