name: 'Travis Reynolds'
description: 'An action to automatically deploy a JammeryHQ starter.'
author: 'JammeryHQ'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
